In [1]:
import numpy as np

Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [2]:
np.arange(10,-1,-1,dtype = np.int32)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0], dtype=int32)

In [3]:
np.linspace(10,0,11,dtype = np.int32)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0], dtype=int32)

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [4]:
def create_diag_matrix(N):
  diag_mat = np.diag(np.arange(N,-1,-1,dtype = np.int32), k=0)
  diag_sum = np.sum(diag_mat)
  return diag_mat, diag_sum

In [5]:
diag_mat,diag_sum = create_diag_matrix(10)

In [6]:
diag_mat

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [7]:
diag_sum

55

Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [8]:
eq_1 = [4, 2, 1]
eq_2 = [1, 3, 0]
eq_3 = [0, 5, 4] 
res = [4, 12, -3]

answ = np.linalg.solve([eq_1,eq_2,eq_3], res)
x = answ[0]
y = answ[1]
z = answ[2]
print('x =',x)
print('y =',y)
print('z =',z)

x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555


In [9]:
np.allclose(np.dot([eq_1,eq_2,eq_3], answ), res) 

True

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

# Скалярное произведение векторов

\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = |\vec{a}| \space |\vec{b}| \space cos(\vec{a}, \vec{b})
\end{equation*}

Пусть 
\begin{equation*}
\LARGE
\vec{a} = (a_1, a_2, a_3) \\
\LARGE
\vec{b} = (b_1, b_2, b_3)
\end{equation*}

Тогда скалярное произведение векторов равно
\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = a_1 b_1 + a_2 b_2 + a_3 b_3
\end{equation*}

# Косинусное сходство между векторами

\begin{equation*}
\LARGE
cos(\vec{a}, \vec{b}) = \frac{\vec{a} \dot{} \vec{b}}{|\vec{a}| \space |\vec{b}|}
\end{equation*}

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
def who_is_similar(users_stats,next_user_stats):
   numerator = np.dot(users_stats,next_user_stats.T)
   norm_users_stats = np.linalg.norm(users_stats, axis = 1)
   norm_next_user_stats = np.linalg.norm(users_stats)
   denominator = norm_users_stats * norm_next_user_stats
   cosine_metric = numerator/denominator 
   return np.argmax(cosine_metric)

In [13]:
user_similar_index = who_is_similar(users_stats,next_user_stats)
user_similar_index

7

In [14]:
users_stats[user_similar_index,:]

array([0, 1, 1, 0, 0, 0], dtype=int32)